// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnjtbihtulubqbafqdus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuanRiaWh0dWx1YnFiYWZxZHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzQ5ODMsImV4cCI6MjA3MjE1MDk4M30.T2yPZrADh2lwYaXg6UzDz-563vLWj4oU8XX0uZJ7ohI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});